---
  - name: Installs nginx web server
    apt: pkg=nginx state=installed update_cache=true
    notify:
      - restart nginx
      
  - name: Copy nginx configuration for selix application
    template: src=default dest=/etc/nginx/sites-available/default
    notify:
      - restart nginx
